(function () {
  window.HrrraConfig = {
    canvasWidth: 1200,
    canvasHeight: 700,

    topDeathLineY: 90,
    bottomDeathLineY: 650,

    worldAutoRunSpeed: 200,
    speedStepScore: 1000,
    speedStepMultiplier: 1.1,
    cameraAnchorRatio: 0.25,

    playerSize: 40,
    doubleJumpUnlockScore: 2500,
    doubleJumpIconSizeRatio: 0.75,
    doubleJumpEffectSeconds: 10,
    doubleJumpRespawnMinSeconds: 5,
    doubleJumpRespawnMaxSeconds: 15,
    slowUnlockSpeedPercent: 200,
    slowIconSizeRatio: 1.2,
    slowRespawnMinSeconds: 10,
    slowRespawnMaxSeconds: 20,
    scoreBagBonus: 2000,
    scoreBagIconSizeRatio: 1.05,
    scoreBagRespawnMinSeconds: 5,
    scoreBagRespawnMaxSeconds: 20,
    coinScoreBonus: 200,
    coinIconSizeRatio: 0.78,
    platformCoinInitialDelaySeconds: 3,
    platformCoinRespawnMinSeconds: 0.5,
    platformCoinRespawnMaxSeconds: 2,
    elevatorCoinMinPerShaft: 1,
    elevatorCoinMaxPerShaft: 3,
    moveSpeedGround: 230,
    moveSpeedAir: 70,
    gravity: 1900,
    jumpInitialVelocity: 580,
    jumpHoldAcceleration: 1200,
    jumpHoldMaxTime: 0.12,
    maxFallSpeed: 1300,

    platformHeight: 12,
    platformY: 520,
    platformLengthMultiplier: 1.5,
    platformVerticalDeltaRatio: 0.2,
    platformTopSafetyMargin: 12,
    platformBottomSafetyMargin: 24,
    stackedPlatformMinInterval: 3,
    stackedPlatformMaxInterval: 6,
    stackedGapMinPlayerHeightMultiplier: 4,
    stackedGapMaxJumpMultiplier: 2,
    widthExpandMaxMultiplier: 1.5,
    safeSectionMin: 280,
    safeSectionMax: 420,
    shaftWidthMin: 280,
    shaftWidthMax: 360,

    elevatorWidth: 88,
    elevatorWidthMaxMultiplier: 1.5,
    elevatorHeight: 12,
    elevatorSpeed: 95,
    elevatorMinCount: 2,
    elevatorMaxCount: 4,
    elevatorMaxStepX: 170,
    elevatorBottomOffset: 18,
    elevatorTopOffset: 40,

    generateAheadDistance: 2600,
    cleanupBehindDistance: 500
  };
})();
